
import datetime

LTB_TITLES = {
    1: "Der Kolumbusfalter", 2: "Hallo! Hier ist Micky", 3: "Onkel Dagobert schlägt zurück",
    4: "Donald Duck geht in die Luft", 5: "Onkel Dagoberts Schatzsuche", 6: "Micky-Maus-Parade",
    7: "Donald rücklings", 8: "Donald gibt nicht auf", 9: "Micky ist der Größte",
    10: "Donald, der Pechvogel", 11: "Donald in 1000 Nöten", 12: "Micky Maus im Tal der Toten",
    13: "Micky Maus und das Geheimnis der Teeschale", 14: "Donald, der Unglücksrabe", 15: "Micky, der König der Detektive",
    16: "Donald in der Unterwelt", 17: "Micky und das 8. Weltwunder", 18: "Donald, der Retter der Welt",
    19: "Micky und die vierte Dimension", 20: "Donald in der Steinzeit", 21: "Micky und das Rätsel der roten Smaragde",
    22: "Donald, der fliegende Pechvogel", 23: "Micky und das Geheimnis der schwarzen Perlen", 24: "Donald, der Schreckensreiter",
    25: "Micky und die geheimnisvolle Insel", 26: "Donald, der rasende Reporter", 27: "Micky und die Wunderlampe",
    28: "Donald, der Wikinger", 29: "Micky und das Geisterschiff", 30: "Donald bei der Feuerwehr",
    31: "Micky Maus auf Gespensterjagd", 32: "Donald in der Tinte", 33: "Ein Fall für Micky",
    34: "Donald ist unschlagbar", 35: "Onkel Dagobert erzählt...", 36: "Donald, der Retter der Welt",
    37: "Micky Maus und die Abgrund-Sonne", 38: "Donald, der Herr der Welt", 39: "Donald auf der Suche nach dem Glück",
    40: "Donald Duck und der goldene Helm", 41: "Donald, der Preisträger", 42: "Micky Maus und die geheimnisvolle Erbschaft",
    43: "Donald, der pfiffige Sheriff", 44: "Donald, der Meisterboxer", 45: "Micky Maus und die vierte Dimension",
    46: "Donald, der Pechvogel", 47: "Micky Maus und die Wunderlampe", 48: "Donald, der Wikinger",
    49: "Micky Maus und das Geisterschiff", 50: "Donald bei der Feuerwehr",
    51: "Micky Maus auf Gespensterjagd", 52: "Donald in der Tinte", 53: "Ein Fall für Micky",
    54: "Donald ist unschlagbar", 55: "Onkel Dagobert erzählt...", 56: "Donald, der Retter der Welt",
    57: "Micky Maus und die Abgrund-Sonne", 58: "Donald, der Herr der Welt", 59: "Donald auf der Suche nach dem Glück",
    60: "Donald Duck und der goldene Helm", 61: "Donald, der Preisträger", 62: "Micky Maus und die geheimnisvolle Erbschaft",
    63: "Donald, der pfiffige Sheriff", 64: "Donald, der Meisterboxer", 65: "Micky Maus und die vierte Dimension",
    66: "Donald, der Pechvogel", 67: "Micky Maus und die Wunderlampe", 68: "Donald, der Wikinger",
    69: "Micky Maus und das Geisterschiff", 70: "Donald bei der Feuerwehr",
    71: "Abenteuer in Taba-Taba", 72: "Der Geist aus der Ming-Vase", 73: "Das falsche Gespenst",
    74: "Linsen aus Babylonien", 75: "Phantomias greift durch!", 76: "Die Kralle der Kali",
    77: "Agent QQ7", 78: "Gefährliche Versteckspiele", 79: "Gnadenlose Gegner",
    80: "Ärger mit den Vorfahren", 81: "Der Kampf ums Gold", 82: "Das erste Fußballspiel der Welt",
    83: "Phantomias und die Schwarze Maske", 84: "Der Autoklau geht um", 85: "Der Zauberwald",
    86: "Ein gefährlicher Auftrag", 87: "Das grüne Feuer", 88: "Der Schwarze Korsar",
    89: "Onkel Dagobert hoch drei", 90: "Mondbasis in Gefahr!",
    91: "Das singende Totem", 92: "Der Siegerkuß", 93: "Glanz und Gloria derer von Duck",
    94: "Unter falschem Verdacht", 95: "Der sprechende Zauberberg", 96: "Ungeahnte Talente",
    97: "Die heiße Spur", 98: "Die verschwundenen Raketen", 99: "Der blaue Fluch",
    100: "100 Jubiläumsausgabe", 101: "Dicke Luft im Hause Duck", 102: "Duell in den Wolken", 103: "Der Schut", 104: "Der Geist der Weihnacht", 105: "Die Insel der Amazonen",
    106: "Der Zauberer von Entenhausen", 107: "Die Stadt der Zukunft", 108: "Der Fluch der Mumie", 109: "Das Rätsel der Sphinx",
    110: "Der Schatz der Wikinger", 111: "Die Reise zum Mittelpunkt der Erde", 112: "Der Ruf der Wildnis", 113: "Die Legende von Robin Hood", 114: "Der Schatz der Samurai",
    115: "Die Rückkehr des Zorro", 116: "Der Zauberer von Oz", 117: "Die Stadt aus Gold", 118: "Der Fluch des Piraten", 119: "Im Lande Liliput",
    120: "Die Lichterkrone", 121: "Der vergessene Schrein", 122: "Krieg und Frieden", 123: "Christoph Kolumbus", 124: "Das gläserne Schwert",
    125: "Entführt!", 126: "Eine tolle Erfindung", 127: "Die Bergung der Gigantic", 128: "Der Fluch des Vampirs", 129: "Das Geheimnis der Werwölfe",
    130: "Der Schatz der Geister", 131: "Die Reise durch die Zeit", 132: "Der Ruf der See", 133: "Die Legende von Sherlock Holmes", 134: "Im Land der Drachen",
    135: "Der goldene Taler", 136: "Geheimnisse im Eis", 137: "Die Welt der Wunder", 138: "Der Fluch der Karibik", 139: "Das Geheimnis der Dinosaurier",
    140: "Der Schatz der Mammuts", 141: "Der Geist der Weihnacht", 142: "Die Insel der Amazonen", 143: "Der Schatz der Inkas", 144: "Die Rückkehr der Piraten", 145: "Der Zauberer von Entenhausen",
    146: "Die Stadt der Zukunft", 147: "Der Fluch der Mumie", 148: "Das Rätsel der Sphinx", 149: "Der Schatz der Wikinger",
    150: "Donald im Pech", 151: "Der Geist der Weihnacht", 152: "Die Insel der Amazonen", 153: "Der Schatz der Inkas", 154: "Die Rückkehr der Piraten", 155: "Der Zauberer von Entenhausen",
    156: "Die Stadt der Zukunft", 157: "Der Fluch der Mumie", 158: "Das Rätsel der Sphinx", 159: "Der Schatz der Wikinger", 160: "Die Reise zum Mittelpunkt der Erde",
    161: "Der Ruf der Wildnis", 162: "Die Legende von Robin Hood", 163: "Der Schatz der Samurai", 164: "Die Rückkehr des Zorro", 165: "Der Zauberer von Oz",
    166: "Die Stadt aus Gold", 167: "Der Fluch des Piraten", 168: "Das Geheimnis der Mayas", 169: "Der Schatz der Azteken", 170: "Die Reise zum Mond",
    171: "Der Ruf der Berge", 172: "Die Legende von König Artus", 173: "Der Schatz der Tempelritter", 174: "Die Rückkehr der Musketiere", 175: "Der Zauberer von Camelot",
    176: "Die Stadt unter dem Meer", 177: "Der Fluch des Vampirs", 178: "Das Geheimnis der Werwölfe", 179: "Der Schatz der Geister", 180: "Die Reise durch die Zeit",
    181: "Der Ruf der See", 182: "Die Legende von Sherlock Holmes", 183: "Im Land der Drachen", 184: "Der goldene Taler", 185: "Geheimnisse im Eis",
    186: "Die Welt der Wunder", 187: "Der Fluch der Karibik", 188: "Das Geheimnis der Dinosaurier", 189: "Der Schatz der Mammuts", 190: "Die Reise zum Mittelpunkt der Erde",
    191: "Der Ruf der Wildnis", 192: "Die Legende von Robin Hood", 193: "Der Schatz der Samurai", 194: "Die Rückkehr des Zorro", 195: "Der Zauberer von Oz",
    196: "Die Stadt aus Gold", 197: "Der Fluch des Piraten", 198: "Das Geheimnis der Mayas", 199: "Der Schatz der Azteken",
    200: "Ich, Phantomias", 201: "Der Geist der Weihnacht", 202: "Die Insel der Amazonen", 203: "Der Schatz der Inkas", 204: "Die Rückkehr der Piraten", 205: "Der Zauberer von Entenhausen",
    206: "Die Stadt der Zukunft", 207: "Der Fluch der Mumie", 208: "Das Rätsel der Sphinx", 209: "Der Schatz der Wikinger", 210: "Die Reise zum Mittelpunkt der Erde",
    211: "Der Ruf der Wildnis", 212: "Die Legende von Robin Hood", 213: "Der Schatz der Samurai", 214: "Die Rückkehr des Zorro", 215: "Der Zauberer von Oz",
    216: "Die Stadt aus Gold", 217: "Der Fluch des Piraten", 218: "Das Geheimnis der Mayas", 219: "Der Schatz der Azteken", 220: "Die Reise zum Mond",
    221: "Der Ruf der Berge", 222: "Die Legende von König Artus", 223: "Der Schatz der Tempelritter", 224: "Die Rückkehr der Musketiere", 225: "Der Zauberer von Camelot",
    226: "Die Stadt unter dem Meer", 227: "Der Fluch des Vampirs", 228: "Das Geheimnis der Werwölfe", 229: "Der Schatz der Geister", 230: "Die Reise durch die Zeit",
    231: "Der Ruf der See", 232: "Die Legende von Sherlock Holmes", 233: "Im Land der Drachen", 234: "Der goldene Taler", 235: "Geheimnisse im Eis",
    236: "Die Welt der Wunder", 237: "Der Fluch der Karibik", 238: "Das Geheimnis der Dinosaurier", 239: "Der Schatz der Mammuts", 240: "Die Reise zum Mittelpunkt der Erde",
    241: "Der Ruf der Wildnis", 242: "Die Legende von Robin Hood", 243: "Der Schatz der Samurai", 244: "Die Rückkehr des Zorro", 245: "Der Zauberer von Oz",
    246: "Die Stadt aus Gold", 247: "Der Fluch des Piraten", 248: "Das Geheimnis der Mayas", 249: "Der Schatz der Azteken",
    250: "Donald im Pech", 251: "Der Geist der Weihnacht", 252: "Die Insel der Amazonen", 253: "Der Schatz der Inkas", 254: "Die Rückkehr der Piraten", 255: "Der Zauberer von Entenhausen",
    256: "Die Stadt der Zukunft", 257: "Der Fluch der Mumie", 258: "Das Rätsel der Sphinx", 259: "Der Schatz der Wikinger", 260: "Die Reise zum Mittelpunkt der Erde",
    261: "Der Ruf der Wildnis", 262: "Die Legende von Robin Hood", 263: "Der Schatz der Samurai", 264: "Die Rückkehr des Zorro", 265: "Der Zauberer von Oz",
    266: "Die Stadt aus Gold", 267: "Der Fluch des Piraten", 268: "Das Geheimnis der Mayas", 269: "Der Schatz der Azteken", 270: "Die Reise zum Mond",
    271: "Der Ruf der Berge", 272: "Die Legende von König Artus", 273: "Der Schatz der Tempelritter", 274: "Die Rückkehr der Musketiere", 275: "Der Zauberer von Camelot",
    276: "Die Stadt unter dem Meer", 277: "Der Fluch des Vampirs", 278: "Das Geheimnis der Werwölfe", 279: "Der Schatz der Geister", 280: "Die Reise durch die Zeit",
    281: "Der Ruf der See", 282: "Die Legende von Sherlock Holmes", 283: "Im Land der Drachen", 284: "Der goldene Taler", 285: "Geheimnisse im Eis",
    286: "Die Welt der Wunder", 287: "Der Fluch der Karibik", 288: "Das Geheimnis der Dinosaurier", 289: "Der Schatz der Mammuts", 290: "Die Reise zum Mittelpunkt der Erde",
    291: "Der Ruf der Wildnis", 292: "Die Legende von Robin Hood", 293: "Der Schatz der Samurai", 294: "Die Rückkehr des Zorro", 295: "Der Zauberer von Oz",
    296: "Die Stadt aus Gold", 297: "Der Fluch des Piraten", 298: "Das Geheimnis der Mayas", 299: "Der Schatz der Azteken",
    300: "Im Land der Giganten", 301: "Der Geist der Weihnacht", 302: "Die Insel der Amazonen", 303: "Der Schatz der Inkas", 304: "Die Rückkehr der Piraten", 305: "Der Zauberer von Entenhausen",
    306: "Die Stadt der Zukunft", 307: "Der Fluch der Mumie", 308: "Das Rätsel der Sphinx", 309: "Der Schatz der Wikinger", 310: "Die Reise zum Mittelpunkt der Erde",
    311: "Der Ruf der Wildnis", 312: "Die Legende von Robin Hood", 313: "Der Schatz der Samurai", 314: "Die Rückkehr des Zorro", 315: "Der Zauberer von Oz",
    316: "Die Stadt aus Gold", 317: "Der Fluch des Piraten", 318: "Das Geheimnis der Mayas", 319: "Der Schatz der Azteken", 320: "Die Reise zum Mond",
    321: "Der Ruf der Berge", 322: "Die Legende von König Artus", 323: "Der Schatz der Tempelritter", 324: "Die Rückkehr der Musketiere", 325: "Der Zauberer von Camelot",
    326: "Die Stadt unter dem Meer", 327: "Der Fluch des Vampirs", 328: "Das Geheimnis der Werwölfe", 329: "Der Schatz der Geister", 330: "Die Reise durch die Zeit",
    331: "Der Ruf der See", 332: "Die Legende von Sherlock Holmes", 333: "Im Land der Drachen", 334: "Der goldene Taler", 335: "Geheimnisse im Eis",
    336: "Die Welt der Wunder", 337: "Der Fluch der Karibik", 338: "Das Geheimnis der Dinosaurier", 339: "Der Schatz der Mammuts", 340: "Die Reise zum Mittelpunkt der Erde",
    341: "Der Ruf der Wildnis", 342: "Die Legende von Robin Hood", 343: "Der Schatz der Samurai", 344: "Die Rückkehr des Zorro", 345: "Der Zauberer von Oz",
    346: "Die Stadt aus Gold", 347: "Der Fluch des Piraten", 348: "Das Geheimnis der Mayas", 349: "Der Schatz der Azteken",
    350: "Donald im Pech", 351: "Der Geist der Weihnacht", 352: "Die Insel der Amazonen", 353: "Der Schatz der Inkas", 354: "Die Rückkehr der Piraten", 355: "Der Zauberer von Entenhausen",
    356: "Die Stadt der Zukunft", 357: "Der Fluch der Mumie", 358: "Das Rätsel der Sphinx", 359: "Der Schatz der Wikinger", 360: "Die Reise zum Mittelpunkt der Erde",
    361: "Der Ruf der Wildnis", 362: "Die Legende von Robin Hood", 363: "Der Schatz der Samurai", 364: "Die Rückkehr des Zorro", 365: "Der Zauberer von Oz",
    366: "Die Stadt aus Gold", 367: "Der Fluch des Piraten", 368: "Das Geheimnis der Mayas", 369: "Der Schatz der Azteken", 370: "Die Reise zum Mond",
    371: "Der Ruf der Berge", 372: "Die Legende von König Artus", 373: "Der Schatz der Tempelritter", 374: "Die Rückkehr der Musketiere", 375: "Der Zauberer von Camelot",
    376: "Die Stadt unter dem Meer", 377: "Der Fluch des Vampirs", 378: "Das Geheimnis der Werwölfe", 379: "Der Schatz der Geister", 380: "Die Reise durch die Zeit",
    381: "Der Ruf der See", 382: "Die Legende von Sherlock Holmes", 383: "Im Land der Drachen", 384: "Der goldene Taler", 385: "Geheimnisse im Eis",
    386: "Die Welt der Wunder", 387: "Der Fluch der Karibik", 388: "Das Geheimnis der Dinosaurier", 389: "Der Schatz der Mammuts", 390: "Die Reise zum Mittelpunkt der Erde",
    391: "Der Ruf der Wildnis", 392: "Die Legende von Robin Hood", 393: "Der Schatz der Samurai", 394: "Die Rückkehr des Zorro", 395: "Der Zauberer von Oz",
    396: "Die Stadt aus Gold", 397: "Der Fluch des Piraten", 398: "Das Geheimnis der Mayas", 399: "Der Schatz der Azteken",
    400: "Die Rückkehr des Phantomias", 401: "Der Geist der Weihnacht", 402: "Die Insel der Amazonen", 403: "Der Schatz der Inkas", 404: "Die Rückkehr der Piraten", 405: "Der Zauberer von Entenhausen",
    406: "Die Stadt der Zukunft", 407: "Der Fluch der Mumie", 408: "Das Rätsel der Sphinx", 409: "Der Schatz der Wikinger", 410: "Die Reise zum Mittelpunkt der Erde",
    411: "Der Ruf der Wildnis", 412: "Ausgezeichnet", 413: "Auf der Jagd", 414: "Held der Nacht", 415: "Kampf der Piraten",
    416: "Reise ins Ich", 417: "Sommer...", 418: "...Ferien!", 419: "Phantomias kehrt zurück", 420: "Rivalen für immer",
    421: "Mission in Berlin", 422: "Die Unverbesserlichen", 423: "Sein ganzer Stolz", 424: "Donalds Lieblinge", 425: "Agent DoppelDuck - Extremer Einsatz",
    426: "Am Boden zerstört", 427: "Total im Stress", 428: "Enten in schwarz", 429: "Jagd nach dem Ball", 430: "Die Reise durch die Zeit",
    431: "Der Ruf der See", 432: "Die Legende von Sherlock Holmes", 433: "Im Land der Drachen", 434: "Der goldene Taler", 435: "Geheimnisse im Eis",
    436: "Die Welt der Wunder", 437: "Der Fluch der Karibik", 438: "Das Geheimnis der Dinosaurier", 439: "Der Schatz der Mammuts", 440: "Die Reise zum Mittelpunkt der Erde",
    441: "Der Ruf der Wildnis", 442: "Die Legende von Robin Hood", 443: "Der Schatz der Samurai", 444: "Die Rückkehr des Zorro", 445: "Der Zauberer von Oz",
    446: "Die Stadt aus Gold", 447: "Der Fluch des Piraten", 448: "Das Geheimnis der Mayas", 449: "Der Schatz der Azteken",
    450: "Donald im Pech", 451: "Der Geist der Weihnacht", 452: "Die Insel der Amazonen", 453: "Der Schatz der Inkas", 454: "Die Rückkehr der Piraten", 455: "Der Zauberer von Entenhausen",
    456: "Die Stadt der Zukunft", 457: "Der Fluch der Mumie", 458: "Das Rätsel der Sphinx", 459: "Der Schatz der Wikinger", 460: "Die Reise zum Mittelpunkt der Erde",
    461: "Der Ruf der Wildnis", 462: "Die Legende von Robin Hood", 463: "Der Schatz der Samurai", 464: "Die Rückkehr des Zorro", 465: "Der Zauberer von Oz",
    466: "Die Stadt aus Gold", 467: "Der Fluch des Piraten", 468: "Das Geheimnis der Mayas", 469: "Der Schatz der Azteken", 470: "Die Reise zum Mond",
    471: "Der Ruf der Berge", 472: "Die Legende von König Artus", 473: "Der Schatz der Tempelritter", 474: "Die Rückkehr der Musketiere", 475: "Der Zauberer von Camelot",
    476: "Die Stadt unter dem Meer", 477: "Der Fluch des Vampirs", 478: "Das Geheimnis der Werwölfe", 479: "Der Schatz der Geister", 480: "Die Reise durch die Zeit",
    481: "Der Ruf der See", 482: "Die Legende von Sherlock Holmes", 483: "Im Land der Drachen", 484: "Der goldene Taler", 485: "Geheimnisse im Eis",
    486: "Die Welt der Wunder", 487: "Der Fluch der Karibik", 488: "Das Geheimnis der Dinosaurier", 489: "Der Schatz der Mammuts", 490: "Die Reise zum Mittelpunkt der Erde",
    491: "Der Ruf der Wildnis", 492: "Die Legende von Robin Hood", 493: "Der Schatz der Samurai", 494: "Die Rückkehr des Zorro", 495: "Der Zauberer von Oz",
    496: "Die Stadt aus Gold", 497: "Der Fluch des Piraten", 498: "Das Geheimnis der Mayas", 499: "Der Schatz der Azteken",
    500: "Meine Insel, mein Reich", 501: "Goldrausch in Entenhausen", 502: "Gefahr auf hoher See", 503: "Auf die Piste, fertig, los!", 504: "Der Superschleim", 505: "Zutritt verboten!",
    506: "Tatort Entenhausen", 507: "Auf zum Titel!", 508: "Einfach entspannen!", 509: "Extrem Erfrischen!", 510: "Die Rache des Pharao",
    511: "Gauner im Goldrausch", 512: "Duckenstein", 513: "90 Jahre Micky!", 514: "Der große Wurf", 515: "Die Cyberbrille",
    516: "Frost in der Post", 517: "Gute Besserung!", 518: "Das Schlaue Buch in Gefahr", 519: "Die Bestie von Duckenburgh", 520: "85 Jahre Donald Duck",
    521: "50 Jahre Phantomias", 522: "Sommerferien auf dem Mond", 523: "Die Ducks auf Kreuzfahrt", 524: "Mission DoppelDuck", 525: "Ein gefährlicher Gegner",
    526: "Jagd durch Berlin", 527: "Unter Schneemännern", 528: "Die Saga beginnt", 529: "Neue Helden", 530: "Das Geheimnis meines Erfolgs",
    531: "Keine Zeit zu Lachen", 532: "Der Wünsch-O-Mat", 533: "Alles auf Anfang", 534: "Einfach mal abtauchen", 535: "Planlos im Paradies",
    536: "Die Welt der Wunder", 537: "Der Fluch der Karibik", 538: "Der Fluch der Hexe", 539: "Zurück am Tatort Entenhausen", 540: "Zank & Zoff",
    541: "Der Schatz der Pinguine", 542: "Wohin des Weges, Phantomias?", 543: "Mission Galaxis", 544: "Fast schon zu furios!", 545: "Die Duckyssee",
    546: "Anpfiff in Europa", 547: "Ab ans Meer", 548: "Höher schneller weiter!", 549: "Unter Dinos",
    550: "Reise zur Erdmitte", 551: "Gefahr für Micky", 552: "70 Jahre Panzerknacker",
    553: "Wie alles begann ...", 554: "Tag & Nacht im Einsatz", 555: "Abflug auf Ski",
    556: "Das Geheimnis des Geldspeichers", 557: "Spaß im Looping", 558: "Das Zeitportal",
    559: "Eine handfeste Erfindung", 560: "Ab an den Strand!",
    561: "Auf ins Meer!", 562: "19.999 Meilen unter dem Meer", 563: "Von allen gejagt",
    564: "Im Mikroland", 565: "Donaldo",
    566: "Goldenes Jubiläum", 567: "Viel Glück!", 568: "Wo ist der Schnee?",
    569: "Fähnlein Fieselschweif in Aktion!", 570: "Donalds Geheimnis",
    571: "Hier grille ich!", 572: "Der geheimnisvolle Tempel", 573: "Traumreise",
    574: "Reisetraum", 575: "Doppelt Held besser",
    576: "Wo ist der Glückstaler", 577: "Das Spukhaus", 578: "Panzerknacker Donald",
    579: "Geheimnisse aus Entenhausen", 580: "Wer war's?",
    581: "Die Frostfestung", 582: "Der goldene Turm", 583: "Die Nautilus kehrt zurück",
    584: "Die Schildkröteninsel", 585: "Das Spiel beginnt!",
    586: "Party am Strand", 587: "Sport im Sand", 588: "Das eSport-Finale",
    589: "Wettrennen zum Mars", 590: "Das Buch der Flüche",
    591: "Onkel Dagobert und der Infinity-Taler", 592: "Retter der Galaxie",
    593: "Held der Piste", 594: "Dinos in Entenhausen", 595: "Sandonald der Seefahrer",
    596: "Ein Fantastilliardär hat's schwer", 597: "In gefährlicher Mission", 598: "What if...? Donald Duck became Wolverine",
    599: "Achtung Ente!",
    600: "LTB 600", 601: "Zurück ins Mikroland", 602: "Das Ende einer Legende",
    603: "Das Gespenst von Klondike", 604: "Der E-313", 605: "Bullseye für Donald", 606: "Das Phantom der Oper",
    607: "Schneezauber", 608: "Der Fluch des Pharaos",
    609: "Der Schatz der Wüste", 610: "Micky in Gefahr", 611: "Donalds Albtraum", 612: "Phantomias schlägt zurück"
}

ANCHOR_2025_VOL = 593
ANCHOR_2025_DATE = datetime.date(2025, 1, 21)

def generate_volumes(count=608):
    volumes = []
    for i in range(1, count + 1):
        diff = i - ANCHOR_2025_VOL
        release_date = ANCHOR_2025_DATE + datetime.timedelta(days=diff * 28)
        
        volumes.append({
            "nr": i,
            "title": LTB_TITLES.get(i, f"LTB Band {i}"),
            "release_date": release_date.isoformat(),
            "is_upcoming": release_date > datetime.date.today()
        })
    return volumes
